name: oasdiff pro review
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  pull-requests: write
  statuses: write
jobs:
  pro-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --depth=1 origin ${{ github.base_ref }}
      - uses: oasdiff/oasdiff-action/changelog@feat/e2-changelog-pro-review
        with:
          base: 'origin/${{ github.base_ref }}:simple.yaml'
          revision: 'HEAD:simple.yaml'
          oasdiff-token: 0634345d-02fb-43df-b56a-68fc22253621
          github-token: ${{ github.token }}
